### ISSUE TITLE
Incorrectly specified fields between the Katsu MoH model and the MoH model spreadsheet

### ISSUE THREAD

**Issue by daisieh** [CanDIG/katsu#129]
Starting a list:

* treatment_type in Treatment is specified as an array, but it is specified as a text field in the spreadsheet

**Comment by SonQBChau** [comment]
You are right, but I think it is a mistake from the spreadsheet because the note from Model v2 Feb stated that:

> Depending on the treatment_type(s) selected, additional treatment details may be required to be submitted. For example, if treatment_type includes 'Chemotherapy', the supplemental Chemotherapy treatment type file is required. To include multiple values, separate values with a pipe delimiter '|' within your file.

So it is an array.

**Comment by daisieh** [comment]
In order to make this work for mcoder, I made the following mapping function:
```
# for mapping {mcoder.index_treatment_type(MOHCCN-ABC-0004-Treatment.treatment_type, MOHCCN-ABC-0004-Treatment.submitter_treatment_id)}

def index_treatment_type(data_values):
    curr_id = mappings.peek_at_top_of_stack()
    i = list(data_values["submitter_treatment_id"].values()).pop().index(curr_id["value"])
    return list(data_values["treatment_type"].values()).pop()[i].split('|')
```
