### ISSUE TITLE
uWSGI denies admins access to delete endpoint

### ISSUE THREAD

**Issue by justin-ys** [CanDIG/katsu#131]
Trying to access /katsu/v2/delete/all after the uWSGI changes results in the following error:

`Delete failed with status code 500 and message: [Errno 13] Permission denied: 'chord_metadata_service/mohpackets/data/backup_db'`

**Comment by SonQBChau** [comment]
I removed the function and replace it with the new endpoint in https://github.com/CanDIG/katsu/pull/132
