### ISSUE TITLE
Authenticate for ingesting data

### ISSUE THREAD

**Issue by rjiang9** [CanDIG/katsu#264]
Hi guys, 

I checked out the katsu repo and set it up on my local macbook pro without any issue. I passed all the tests, loaded large or small set of synthetica data.  After that I can visit localhst:8000 and I can check the default/discovery/overview data. 

But I ran into authentication issue when I was trying to ingest some data there. Here was what I did:

1) By clicking 'Authorize' button, I set the values for ingest (all others too) like this:
<img width="436" alt="image" src="https://github.com/user-attachments/assets/a30dd11c-a6af-43ec-8728-c1be73f6e2cd">

2) Scrolled down to the `ingest` section, I clicked on 'Try it out' and then click on 'Execute' button. I got 401 - anthorized message. What did I miss here? 

<img width="956" alt="image" src="https://github.com/user-attachments/assets/afdc7a1f-912b-4154-9ff4-0bffa58ef5aa">

I am thankful if you can give me some hints. 

Thanks,
Ray

**Comment by SonQBChau** [comment]
Hi Ray,

You can find the token values in `config/settings/local.py`. The default values are:

```
QUERY_SERVICE_TOKEN = "query"
INGEST_SERVICE_TOKEN = "candig-ingest"
LOCAL_OPA_DATASET = {"user_1", "user_1", "site_admin"}
```

Feel free to modify them as needed. Let me know if you have any questions.

**Comment by SonQBChau** [comment]
Due to a recent change, you can either use `IngestTokenAuth = candig-ingest` or `IngestAuth = site_admin` to ingest. Also noted that your program_id has to match the value in `write_datasets`

**Comment by rjiang9** [comment]
Works like a charm. Thanks a lot @SonQBChau
