### ISSUE TITLE
Nose tests fail, currently incompatible with python 3.10

### ISSUE THREAD

**Issue by shaikh-rashid** [CanDIG/katsu#43]
The test suite uses nose, which is currently incompatible with python 3.10 https://github.com/xlcnd/isbnlib/issues/95

_Originally posted by @kcranston in https://github.com/CanDIG/katsu/issues/42#issuecomment-1156628921_

**Comment by kcranston** [comment]
The preferred way to write tests in Django uses [unittest](https://docs.python.org/3/library/unittest.html#module-unittest), see https://docs.djangoproject.com/en/4.0/topics/testing/ . Our (candig/katsu + upstream) current setup uses [django-nose](https://docs.python.org/3/library/unittest.html#module-unittest) which is in maintenance mode.

**Comment by cclauss** [comment]
Was this issue fixed in #55 or earlier?

**Comment by SonQBChau** [comment]
fix in #66
