### ISSUE TITLE
When you delete mcodepacket, associated cancer_conditions remain

### ISSUE THREAD

**Issue by kcranston** [CanDIG/katsu#49]
We need to revisit the modeling of `cancer_conditions` in the mcodepacket. Not sure if the many-to-many relationship is the problem, or the `on_delete` setting. This specific example may not be the only case - there may be other parts of of the model that also have the same behaviour. 

Diagnosed by:
1. Create two datasets with the same patients, but one dataset has only a subset of the cancer_conditions fields (`dataset1`) and one has all of the cancer_conditions fields (`dataset2`)
2. Ingest `dataset1` as mcodepackets with [katsu_ingest.py](https://github.com/CanDIG/candigv2-ingest/blob/main/katsu_ingest.py) 
3. Run [katsu_clean.py](https://github.com/CanDIG/candigv2-ingest/blob/main/katsu_clean.py) to delete the dataset
4. Ingest the `dataset2` using katsu_ingest.py
5. Request the mcodepacket from katsu - you should still see the cancer_conditions from dataset1

**Comment by SonQBChau** [comment]
This issue is no longer relevant and can be closed. The candigv2-ingest repository now has a new [clean_data function](https://github.com/CanDIG/candigv2-ingest/blob/main/moh_ingest.py#L76)
