### ISSUE TITLE
authorized_datasets can be directly submitted as a querystring

### ISSUE THREAD

**Issue by daisieh** [CanDIG/katsu#56]
@SonQBChau points out that in the tests for authz, apparently you can just shove a query parameter for authorized_datasets into your API call and it might override whatever OPA says about which datasets should be authorized. We need to make sure that the request's value for authorized_datasets is set to NO_DATASETS_AUTHORIZED whenever CANDIG_AUTHORIZATION is set to OPA to override anything that might've come in on the query parameters.

**Comment by daisieh** [comment]
Specifically this seems to happen here: https://github.com/CanDIG/katsu/blob/efba18c2e2a427362ab1d639d285b6b038053b84/chord_metadata_service/phenopackets/tests/test_api.py#L395

Unless phenopackets is just very different from our OPA middleware? @ppillot might know.

**Comment by daisieh** [comment]
Never mind, it definitely happens in mcode as well and I can't imagine that this test is supposed to work at all.

https://github.com/CanDIG/katsu/blob/efba18c2e2a427362ab1d639d285b6b038053b84/chord_metadata_service/mcode/tests/test_api.py#L68

**Comment by ppillot** [comment]
I guess this test may run without the OPA middleware. In that case it only checks wether the filtering part of the code is working properly.

**Comment by SonQBChau** [comment]
fix in #59
