### ISSUE TITLE
Are allowed_datasets and authorized_datasets the same thing?

### ISSUE THREAD

**Issue by daisieh** [CanDIG/katsu#57]
The authz middleware seems to stuff the information for authorized datasets into a parameter called `authorized_datasets` and the tests seem to agree that the query parameter would be `authorized_datasets`, but throughout the code, e.g. https://github.com/CanDIG/katsu/blob/efba18c2e2a427362ab1d639d285b6b038053b84/chord_metadata_service/mcode/api_views.py#L204

we seem to think that it's `allowed_datasets`. That can't be right. These should be consistent.

**Comment by SonQBChau** [comment]
fixed in #59
