### ISSUE TITLE
Better documentation about CanDIG authorization

### ISSUE THREAD

**Issue by kcranston** [CanDIG/katsu#60]
The only documentation in this repo about CanDIG authorization is a [small section](https://github.com/CanDIG/katsu#authorization-inside-candig) in the readme that only mentions three environment variables that need setting. There is no detail about how the authorization works, which makes it hard to know how the code can and cannot be changed without affecting authorization. 

It may make sense to point to a more general description of how CanDIG authorization works (in the candig-opa repo?) and then just have a small section in this repo that is katsu-specific, in addition to some inline code comments near critical parts of the code.

**Comment by kcranston** [comment]
The details: when CANDIG_AUTHORIZATION = "OPA" then all of the API calls in [api_views](https://github.com/CanDIG/katsu/blob/2409f9c23ed3fc00988c11b687072f6deb345a62/chord_metadata_service/mohpackets/api_views.py) use [this filtering](https://github.com/CanDIG/katsu/blob/2409f9c23ed3fc00988c11b687072f6deb345a62/chord_metadata_service/mohpackets/api_views.py#L79) based on [calling opa](https://github.com/CanDIG/katsu/blob/develop/chord_metadata_service/mohpackets/utils.py#L11) to only return results from authorized datasets for the given user.

**Comment by SonQBChau** [comment]
This issue got updated here: https://github.com/CanDIG/katsu#authentication-and-authorization
